import { Effect, Layer } from "effect";
import { McpServer } from "effect/ai";

export const PrimerResourceLive = Layer.mergeAll(
  McpServer.resource({
    uri: "stack-effect://primer",
    name: "Stack Effect Primer",
    description: "A short introduction to this generated MCP server",
    mimeType: "text/plain",
    content: Effect.succeed(
      "This MCP server was generated by Stack Effect and can be extended with tools, prompts, and resources.",
    ),
  }),
);
